### ISSUE TITLE
Delay when dragging tracklist items

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#171]
Since upgrading ionic to v1.2 (at least), there's a noticeable delay when dragging a tracklist item to another position before the spinner appears. Might be finally necessary to update client copy before sending a `tracklist.move`.

**Comment by tkem** [comment]
Aside from the round-trip for `tracklist.move`, turns out track images are reloaded for every tracklist change. These should be cached, anyway, but will result in another round-trip for a `getImages()` with an empty URI list....

**Comment by tkem** [comment]
Additionally, the `tracklist_changed` event resulting from the move operation (which must be handled anyway, to prevent race conditions, results in another "empty" `getImages()` request.

**Comment by tkem** [comment]
There's still a noticeable delay on Android platforms when dragging list items for reorder. Might be that `$scope.$apply()` is needed for updating the client model.

**Comment by tkem** [comment]
This may be relevant: https://github.com/driftyco/ionic/commit/ba1859b308b0769e4af2e72cb229cb7a87ade0e3
Strangely enough, playlist reordering seems to work smoothly *without* `$apply`. Shouldn't hurt, though.

**Comment by tkem** [comment]
Turns out, wrapping the reorder in a ``$scope.$apply()` does not really improve things. Using ``$scope.$apply()` with item delete even yields
```
234   204481   error    Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.4.3/$rootScope/inprog?p0=%24apply
    at http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:13380:12
    at beginPhase (http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:29512:15)
    at Scope.$apply (http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:29256:11)
    at Scope.$scope.remove (http://192.168.1.101:8100/app/playlists/playlists.js:239:14)
    at fn (eval at <anonymous> (http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:1:0), <anonymous>:4:287)
    at http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:62386:9
    at Scope.$eval (http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:29158:28)
    at Scope.$apply (http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:29257:23)
    at HTMLElement.<anonymous> (http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:62385:13)
    at HTMLElement.eventHandler (http://192.168.1.101:8100/lib/ionic/release/js/ionic.bundle.js:16583:21)
```
So this does *not* seem to be a good idea.

**Comment by tkem** [comment]
Strangely, this seems mostly to occur with the app version.

**Comment by tkem** [comment]
Since this is mostly an app issue, *may* actually be related to Cordova. Since Cordova 6.0.0 was released recently, trying to update wouldn't hurt.

**Comment by tkem** [comment]
Another possible issue could be returning a promise in ionic's `on-move` handler...

**Comment by tkem** [comment]
...which wouldn't explain the delay when reordering *playlist* items, though.

**Comment by tkem** [comment]
Seems to be no longer an issue after upgrading to Ionic v1.3 and switching to `ng-repeat`.
