### ISSUE TITLE
Mute broken in v0.8.6 running against Mopidy 1.0.0

### ISSUE THREAD

**Issue by adamcik** [tkem/mopidy-mobile#36]
UI sent `{"method":"core.mixer.set_mute","params":{"value":true},"jsonrpc":"2.0","id":29}` which resulted in:

```
Traceback (most recent call last):
  File "/home/adamcik/dev/mopidy/mopidy/utils/jsonrpc.py", line 132, in _handle_single_request
    result = self._unwrap_result(result)
  File "/home/adamcik/dev/mopidy/mopidy/utils/jsonrpc.py", line 221, in _unwrap_result
    result = result.get()
  File "build/bdist.linux-x86_64/egg/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "build/bdist.linux-x86_64/egg/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "build/bdist.linux-x86_64/egg/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
TypeError: set_mute() got an unexpected keyword argument 'value'
```

https://docs.mopidy.com/en/latest/api/core/#mopidy.core.MixerController.set_mute so `s/value/mute/` and this should work. Changing mute externally is still handled correctly and I see the updates in the UI.

**Comment by tkem** [comment]
Parameter is `value` in `playback.setMute()` according to Mopidy-API-Explorer, so need to adapt the JS shim for backward compatibility.
